In [1]:
import numpy as np

In [2]:
n = np.random.randint(0, 10, 10000)

In [3]:
h = np.bincount(n)

In [4]:
h

array([ 980, 1022, 1013,  973, 1000,  996, 1059,  975,  994,  988])

In [5]:
h = h / h.sum()

In [6]:
h

array([0.098 , 0.1022, 0.1013, 0.0973, 0.1   , 0.0996, 0.1059, 0.0975,
       0.0994, 0.0988])

In [8]:
t = np.random.binomial(5, 0.3, size=1000)
s = np.bincount(t)
s, s/s.sum()

(array([172, 354, 316, 129,  28,   1]),
 array([0.172, 0.354, 0.316, 0.129, 0.028, 0.001]))

ModuleNotFoundError: No module named 'torch.distributions.Binomial'

In [2]:
t = torch.distributions.binomial.Binomial

AttributeError: module 'torch.random' has no attribute 'binomial'